-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.address_book
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    fullname text COLLATE pg_catalog."default" NOT NULL,
    pa_role text COLLATE pg_catalog."default" NOT NULL,
    legal_structure_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT address_book_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.address_book
    OWNER to postgres;

GRANT ALL ON TABLE public.address_book TO anon;

GRANT ALL ON TABLE public.address_book TO authenticated;

GRANT ALL ON TABLE public.address_book TO postgres;

GRANT ALL ON TABLE public.address_book TO service_role;

COMMENT ON TABLE public.address_book
    IS 'rubrica popolata dal db del personale in base ad una schedulazione';

