-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.address_book
    ADD CONSTRAINT email_u UNIQUE (email);

ALTER TABLE IF EXISTS public.uo
    ADD COLUMN coddesc text COLLATE pg_catalog."default" NOT NULL;
ALTER TABLE IF EXISTS public.uo
    ADD CONSTRAINT coddesc_u UNIQUE (coddesc);



ALTER TABLE IF EXISTS public.info_system
    ADD CONSTRAINT resp_address_fk FOREIGN KEY (resp_email)
    REFERENCES public.address_book (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.info_system
    ADD CONSTRAINT resp_inf_address_fk FOREIGN KEY (resp_inf_email)
    REFERENCES public.address_book (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
